### PR TITLE
Small fix for new_cmake_build

### PR DESCRIPTION
**Pull request by samuelgarcia**
Try to fix the new_cmake_build branch.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@Claybarn @fpbattaglia 

I made many change in the readme.

The procedure for compilation tottaly change with the cmake system.
The  `./build-linux.sh` stuf is no more necessary.

As I only tested onlinux pip+virtualenv.
Could you also help me to make changes for windows and linux+conda ?

**Comment by Claybarn** [comment]
@samuelgarcia yeah can help you with the other builds. I tried on my Mac + Conda but it did not work. Couldn't find the dynamic lib in the rpath. Might have better luck on a different system.

**Comment by samuelgarcia** [comment]
Did you recompile the new version plugin-GUI 0.5 with the same compiler ?
This is trick with unbuntu20.4 gcc-8 only and the default is gcc-9.
Did you inspect CMAkeLists.txt from other plugins ?

**Comment by samuelgarcia** [comment]
Any news here ?
I have recompile today the latest  plugin-GUI version (0.5.2) and so recompile the PythonPlugin.
The recipe I propose is still working with this latest version.
I think you can merge this.

Then we will be able to fix for other system / distro.

**Comment by Claybarn** [comment]
Have some time to spend on testing it myself tomorrow, will let you know!

**Pull request merged**
