### PR TITLE
use samp rate of input unless you're a source

### PR DESCRIPTION
**Pull request by beOn**
addresses https://github.com/MemDynLab/PythonPlugin/issues/10

### CODE REVIEW

**Comment by Claybarn** [comment]
Still got 44100 as the sampling rate. Did it work on your end?

**Comment by beOn** [comment]
Yes, but there’s a bit of a trick to it.  First,  The python plug-in has
to be a filter or sink.  Second, it only picks up the correct sampling rate
if you add the plug-in to the end of a signal chain that already has some
active channels. That’s a bug, for sure.

Addressing it should be pretty easy. I just need to pass sample rate
updates into python whenever the plug-in node receives them.

 If your observation doesn’t make sense in light of this information, give
me whatever details I’ll need for a repro and I’ll fix it.

 Apologies for my spotty availability – there’s a lot going on in the lab
right now and spare cycles are hard to come by!

**Comment by ethanbb** [comment]
So basically we need to add an update function in Python that receives the current sample rate whenever the processor's `updateSettings` function is called, correct?

I would also add the current number of channels and which channels are selected in the "params" tab to the info passed into an update function. Being able to react to changes to these 3 pieces of information before acquisition starts would be a big improvement.

I can draft this feature if nobody else is working on it.

**Comment by fpbattaglia** [comment]
that'd be fantastic, thanks Ethan!

**Comment by beOn** [comment]
All yours, @ethanbb.

**Pull request merged**
